### ISSUE TITLE
Value Error

### ISSUE THREAD

**Issue by zakcay** [ZhiGroup/pytorch_ehr#23]
Hi, 
First, I'd like to thank you for this repository. It has very clear instructions and useful files.

I'd like to use your model on AllofUs database. I've created my case and control files as instructed. The data_processing_v1.py successfully processed it and created the output files with train, valid, test extensions.

Next, I tried to run the models with the command: python3 main.py -root_dir<'your folder that contains data file(s)'> -files<['filename(train)' 'filename(valid)' 'filename(test)']> -which_model<'RNN'> -optimizer<'adam'> 

After encountering some issues and resolving them, I got this error:

Loading and preparing data...
3 files found. 3 dataloaders will be created for each

See an example data structure from training data:
Traceback (most recent call last):
  File "/home/... /main.py", line 288, in <module>
    main()
  File "/home/.../main.py", line 138, in main
    print(train.__getitem__(40, seeDescription = True))
  File "/home/.../EHRDataloader.py", line 99, in __getitem__
    vistc = np.asarray(sample[2])
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (436, 2) + inhomogeneous part.

What do you recommend that I do for troubleshooting? Does this have to do with patient visits having icd codes more than the maximum token size allowed? 

Thank you very much for your guidance.

Side note: When trying to run the main.py file, I got a few errors. The first one being "unterminated string literal (detected at line 70)". I fixed that and the other few and was able to have it running.

**Comment by lrasmy** [comment]
Hi @zakcay,

This is an issue with the numpy version, please make sure you use numpy 1.23 or lower

**Comment by lrasmy** [comment]
Thanks for the side note, which branch are you using the main or the Clinician one?

**Comment by zakcay** [comment]
Thank you so much for pointing out the error source being the numpy version.

The errors I previously mentioned are in this file:
https://github.com/ZhiGroup/pytorch_ehr/blob/master/ehr_pytorch/main.py
There is a missing ' at the end and maybe another error of same type.

So, I reattempted to execute the code. Solved a few errors, got one step closer to the output but this time getting this error:

File "/home/jupyter/... /EHREmb.py", line 89, in EmbedPatients_MB
    embedded = self.embed(mb_t)  ## Embedding for codes
  File "/home/jupyter/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jupyter/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jupyter/.local/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/home/jupyter/.local/lib/python3.10/site-packages/torch/nn/functional.py", line 2233, in embedding
    return **torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self**

Trying to troubleshoot but if you have a quick fix, I'd appreciate it...

**Comment by zakcay** [comment]
Actually, after increasing the input_size I don't get that error but something else instead:

 File "/home/jupyter/.../utils.py", line 77, in trainsample
    loss = criterion(output, label_tensor)    
  File "/home/jupyter/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jupyter/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jupyter/.local/lib/python3.10/site-packages/torch/nn/modules/loss.py", line 618, in forward
    return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
  File "/home/jupyter/.local/lib/python3.10/site-packages/torch/nn/functional.py", line 3113, in binary_cross_entropy
    raise ValueError(
ValueError: Using a target size (torch.Size([128, 1, 1])) that is different to the input size (torch.Size([128])) is deprecated. Please ensure they have the same size.

Any advice?

**Comment by zakcay** [comment]
Actually I was advised to use label_tensor = label_tensor.squeeze(1).squeeze(1) and it worked.

**Comment by lrasmy** [comment]
I see, I'd recommend you to use the Clinician branch, as it is one of the latest, and most of your issues above would be solved there.

Saying so, we will work on updating out Master branch soon as well.

Thanks,
Laila
